# Generated by Django 6.0.6 on 2026-08-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.FloatField(verbose_name='Primeiro número')),
                ('numero2', models.FloatField(verbose_name='Segundo número')),
                ('operacao', models.CharField(choices=[('soma', 'Soma (+)'), ('subtracao', 'Subtração (-)'), ('multiplicacao', 'Multiplicação (*)'), ('divisao', 'Divisão (/)')], max_length=20, verbose_name='Operação')),
                ('resultado', models.FloatField(blank=True, null=True, verbose_name='Resultado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do cálculo')),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
